### ISSUE TITLE
awx image tag ignored

### ISSUE THREAD

**Issue by gmisura** [AdWerx/charts#27]
I wanted to try some older versions of AWX to match my client's tower version (not entirely sure what AWX == to Tower 3.7.5)

I added

```
image:
  tag: "16.0.0"
```

To my values.yml but it was overridden and I got 17.0.1 (not the default 17.1.0).
There any way to use different awx tags?

Thanks

**Comment by jbielick** [comment]
Yep, `image.repository` and `image.tag` are interpolated for the deployment here: https://github.com/AdWerx/charts/blob/36f1484b28b8b42dcde106b01694d2c2798064cc/awx/templates/deployment.yaml#L28

I have no suggestions based on the code sample you provided. There are a lot of ways to provide values in helm, so that may have something to do with what you're seeing.

**Comment by jbielick** [comment]
I've added some tests that I believe verify things work correctly. 

https://github.com/AdWerx/charts/blob/e21628f28d75b24b56ba9d40e20b36c0867ba019/awx/test/unit/deployment.bats#L15-L45

Let me know if I've missed something.

**Comment by gmisura** [comment]
What the heck? I tried exactly that and it didn't work before and now it does! Shesh.
Thanks
